name: "recipes_sharing_app"

services:
  mobile:
    build:
      context: ./apps/mobile
      dockerfile: docker/Dockerfile
    environment:
      - FLUTTER_WEB_PORT=8080
      - FLUTTER_WEB_HOST=0.0.0.0
    ports:
      - "8080:8080"

  web:
    build:
      context: ./apps/web
      dockerfile: docker/Dockerfile
    ports:
      - "80:80"

